// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP9m3TCzh7Npot6hG1gSu0_mfc1mIoMLg',
    appId: '1:592709019519:web:f61f6b5af456db2ffa9c4a',
    messagingSenderId: '592709019519',
    projectId: 'relais-ivoire',
    authDomain: 'relais-ivoire.firebaseapp.com',
    storageBucket: 'relais-ivoire.firebasestorage.app',
    measurementId: 'G-0SR3MRJXDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_DIyxL0lr2ysUw0wgSng7bKiTym2dfU',
    appId: '1:592709019519:android:9b78f29eeeaff51efa9c4a',
    messagingSenderId: '592709019519',
    projectId: 'relais-ivoire',
    storageBucket: 'relais-ivoire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNX_5mUTVG_0J1O8tx-xkEIlCCaak7vxo',
    appId: '1:592709019519:ios:5c0326b74a34ee9dfa9c4a',
    messagingSenderId: '592709019519',
    projectId: 'relais-ivoire',
    storageBucket: 'relais-ivoire.firebasestorage.app',
    iosBundleId: 'com.example.lpr',
  );
}
