// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/AdministrationApp/CustomUser.dart';
import 'models/ClientApp/Client.dart';
import 'models/ClientApp/TypeClient.dart';
import 'models/ColisApp/Colis.dart';
import 'models/ColisApp/StatusColis.dart';
import 'models/ColisApp/TypeColis.dart';
import 'models/ColisApp/TypeDestinataire.dart';
import 'models/ColisApp/TypeEmballage.dart';
import 'models/LivraisonApp/TypeVehicule.dart';
import 'models/PointRelaisApp/PointRelais.dart';
import 'models/PointRelaisApp/Schedule.dart';
import 'models/PointRelaisApp/TypePointRelais.dart';
import 'models/PointRelaisApp/TypeService.dart';
import 'models/ZoneApp/Commune.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4721431471128414278),
      name: 'Client',
      lastPropertyId: const obx_int.IdUid(7, 6982971854070826653),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6043243835465266715),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 989075556229341832),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 2370089394767631057)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3688382711679426163),
            name: 'contact',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4256878170152396401),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3447739266578787643),
            name: 'active',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5716007533763238370),
            name: 'typeClientId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 2111193803077463787),
            relationTarget: 'TypeClient'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6982971854070826653),
            name: 'userId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 953989425773746468),
            relationTarget: 'CustomUser')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 553909608184755708),
      name: 'Colis',
      lastPropertyId: const obx_int.IdUid(19, 3093492318003301981),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6381334791049763235),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1459009063704953094),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(4, 4804658713748036424)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2797058269775564889),
            name: 'code',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 128986907007694823),
            name: 'receiverName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7496099983540685076),
            name: 'receiverPhone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6310005666047797379),
            name: 'total',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2033990689415622688),
            name: 'senderId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 3299831063414277957),
            relationTarget: 'Client'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 71855575795140492),
            name: 'receiverId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(6, 799993630667375202),
            relationTarget: 'Client'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2182848375526986310),
            name: 'pointRelaisSenderId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(7, 295170408108840181),
            relationTarget: 'PointRelais'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 307236839153848720),
            name: 'pointRelaisReceiverId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(8, 6428209988390870343),
            relationTarget: 'PointRelais'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 7814041185599256437),
            name: 'typeColisId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(9, 6620364395183363591),
            relationTarget: 'TypeColis'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 7952843797094712506),
            name: 'typeEmballageId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(10, 5480066071372414504),
            relationTarget: 'TypeEmballage'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 4531705171083579134),
            name: 'typeDestinataireId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(11, 3618171776489380685),
            relationTarget: 'TypeDestinataire'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4840026746405838350),
            name: 'statusId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(12, 5552461805079837722),
            relationTarget: 'StatusColis'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 3005487978491512750),
            name: 'dateCreation',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 2947309330015120876),
            name: 'depotDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 6959423010374133914),
            name: 'recuperationDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 723667936126461737),
            name: 'livraisonDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 3093492318003301981),
            name: 'retraitDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 5035577118533419016),
      name: 'Commune',
      lastPropertyId: const obx_int.IdUid(3, 7268126988972641246),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6157756334423457019),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1769952284392140085),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(13, 6846730826984236165)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7268126988972641246),
            name: 'libelle',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 8418584024633772263),
      name: 'CustomUser',
      lastPropertyId: const obx_int.IdUid(4, 1777308265182776357),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4845016821636504669),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5595060975362164057),
            name: 'firstName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1777308265182776357),
            name: 'lastName',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 7414892366663077985),
      name: 'PointRelais',
      lastPropertyId: const obx_int.IdUid(9, 6005213174252232264),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8183360679664598808),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4206447504669873357),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(15, 8772668370075556180)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 477021923602172826),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2882029766255662837),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6491888401221511617),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 107744009895272865),
            name: 'latitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8276164739228310298),
            name: 'longitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6549607941342348716),
            name: 'typeId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(16, 7806018647490230916),
            relationTarget: 'TypePointRelais'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6005213174252232264),
            name: 'communeId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(17, 8637798324417607768),
            relationTarget: 'Commune')
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 8027319072131125910),
            name: 'services',
            targetId: const obx_int.IdUid(13, 6875664215020968538)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(2, 8920152381114644102),
            name: 'schedules',
            targetId: const obx_int.IdUid(6, 6107841104044359834))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 6107841104044359834),
      name: 'Schedule',
      lastPropertyId: const obx_int.IdUid(5, 5363701079899673462),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7133213770600059371),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3653233779091154056),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(18, 8527917064166039693)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3016360836014220518),
            name: 'level_day',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4763436233632623634),
            name: 'available',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5363701079899673462),
            name: 'point_relaisId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(19, 679355071463970888),
            relationTarget: 'PointRelais')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 3091782836706585062),
      name: 'StatusColis',
      lastPropertyId: const obx_int.IdUid(6, 9000879277382204113),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1620721844396669491),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1964593375672164506),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(20, 5311432973260866783)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8427354242433955739),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3912186942365474927),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4222605074898123768),
            name: 'color',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 9000879277382204113),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 8911871289356573162),
      name: 'TypeClient',
      lastPropertyId: const obx_int.IdUid(4, 7784178730143040707),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 9217588733563159132),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6423704070909484885),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(21, 5677963743287531905)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5408320678786603377),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7784178730143040707),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 546951544980843557),
      name: 'TypeColis',
      lastPropertyId: const obx_int.IdUid(11, 7228896036152813023),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5712803988189871976),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 514560305900353188),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(22, 2900331907244974340)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 711971372046634659),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5918174103478459485),
            name: 'level',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4755118681941109914),
            name: 'icone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2940432341308723136),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5307982953358648172),
            name: 'poids_min',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6674848283647341600),
            name: 'poids_max',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 144021082773160898),
            name: 'price',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 146051800347293643),
            name: 'emballageId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(23, 3338425478040202579),
            relationTarget: 'TypeEmballage'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 7228896036152813023),
            name: 'vehiculeId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(24, 6538917802460479739),
            relationTarget: 'TypeVehicule')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(10, 410810462574419385),
      name: 'TypeDestinataire',
      lastPropertyId: const obx_int.IdUid(5, 5920905474668876022),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6696264707932052495),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4922717476864584925),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(25, 6368989476941924440)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3902950775046091100),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6403137921449755499),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5920905474668876022),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(11, 1527065250441925732),
      name: 'TypeEmballage',
      lastPropertyId: const obx_int.IdUid(5, 1666097711662397213),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2049366128577749307),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1610830765819392784),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(26, 3633848795931172958)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6817476989132826960),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7947861680051413837),
            name: 'price',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1666097711662397213),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(12, 8333451743500689618),
      name: 'TypePointRelais',
      lastPropertyId: const obx_int.IdUid(3, 4683038411620768194),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 794083751796581184),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5607567450994015431),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(27, 5518002572035149682)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4683038411620768194),
            name: 'libelle',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(13, 6875664215020968538),
      name: 'TypeService',
      lastPropertyId: const obx_int.IdUid(3, 5707242218961324196),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7156422634134894598),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4408929577050277002),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(28, 3071371138929771680)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5707242218961324196),
            name: 'libelle',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(14, 7769129789684716093),
      name: 'TypeVehicule',
      lastPropertyId: const obx_int.IdUid(5, 4870176126589874638),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2848435643045619508),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3235132092469467393),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(29, 5595622615468194486)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4245286225461512391),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1283009468644382716),
            name: 'icone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4870176126589874638),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(14, 7769129789684716093),
      lastIndexId: const obx_int.IdUid(29, 5595622615468194486),
      lastRelationId: const obx_int.IdUid(2, 8920152381114644102),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [834491364811918451],
      retiredPropertyUids: const [9072266589675690143],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Client: obx_int.EntityDefinition<Client>(
        model: _entities[0],
        toOneRelations: (Client object) => [object.typeClient, object.user],
        toManyRelations: (Client object) => {},
        getId: (Client object) => object.id,
        setId: (Client object, int id) {
          object.id = id;
        },
        objectToFB: (Client object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final contactOffset = fbb.writeString(object.contact);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, contactOffset);
          fbb.addOffset(3, addressOffset);
          fbb.addBool(4, object.active);
          fbb.addInt64(5, object.typeClient.targetId);
          fbb.addInt64(6, object.user.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final contactParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final activeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final object = Client(
              uid: uidParam,
              contact: contactParam,
              address: addressParam,
              active: activeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.typeClient.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.typeClient.attach(store);
          object.user.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.user.attach(store);
          return object;
        }),
    Colis: obx_int.EntityDefinition<Colis>(
        model: _entities[1],
        toOneRelations: (Colis object) => [
              object.sender,
              object.receiver,
              object.pointRelaisSender,
              object.pointRelaisReceiver,
              object.typeColis,
              object.typeEmballage,
              object.typeDestinataire,
              object.status
            ],
        toManyRelations: (Colis object) => {},
        getId: (Colis object) => object.id,
        setId: (Colis object, int id) {
          object.id = id;
        },
        objectToFB: (Colis object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final codeOffset = fbb.writeString(object.code);
          final receiverNameOffset = fbb.writeString(object.receiverName);
          final receiverPhoneOffset = fbb.writeString(object.receiverPhone);
          fbb.startTable(20);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, codeOffset);
          fbb.addOffset(3, receiverNameOffset);
          fbb.addOffset(4, receiverPhoneOffset);
          fbb.addInt64(5, object.total);
          fbb.addInt64(6, object.sender.targetId);
          fbb.addInt64(7, object.receiver.targetId);
          fbb.addInt64(8, object.pointRelaisSender.targetId);
          fbb.addInt64(9, object.pointRelaisReceiver.targetId);
          fbb.addInt64(10, object.typeColis.targetId);
          fbb.addInt64(11, object.typeEmballage.targetId);
          fbb.addInt64(12, object.typeDestinataire.targetId);
          fbb.addInt64(13, object.status.targetId);
          fbb.addInt64(14, object.dateCreation?.millisecondsSinceEpoch);
          fbb.addInt64(15, object.depotDate?.millisecondsSinceEpoch);
          fbb.addInt64(16, object.recuperationDate?.millisecondsSinceEpoch);
          fbb.addInt64(17, object.livraisonDate?.millisecondsSinceEpoch);
          fbb.addInt64(18, object.retraitDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateCreationValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 32);
          final depotDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 34);
          final recuperationDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 36);
          final livraisonDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 38);
          final retraitDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 40);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final codeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final receiverNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final receiverPhoneParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final totalParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final depotDateParam = depotDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(depotDateValue);
          final recuperationDateParam = recuperationDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(recuperationDateValue);
          final livraisonDateParam = livraisonDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(livraisonDateValue);
          final retraitDateParam = retraitDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(retraitDateValue);
          final dateCreationParam = dateCreationValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dateCreationValue);
          final object = Colis(
              id: idParam,
              uid: uidParam,
              code: codeParam,
              receiverName: receiverNameParam,
              receiverPhone: receiverPhoneParam,
              total: totalParam,
              depotDate: depotDateParam,
              recuperationDate: recuperationDateParam,
              livraisonDate: livraisonDateParam,
              retraitDate: retraitDateParam,
              dateCreation: dateCreationParam);
          object.sender.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.sender.attach(store);
          object.receiver.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.receiver.attach(store);
          object.pointRelaisSender.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.pointRelaisSender.attach(store);
          object.pointRelaisReceiver.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.pointRelaisReceiver.attach(store);
          object.typeColis.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          object.typeColis.attach(store);
          object.typeEmballage.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          object.typeEmballage.attach(store);
          object.typeDestinataire.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          object.typeDestinataire.attach(store);
          object.status.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0);
          object.status.attach(store);
          return object;
        }),
    Commune: obx_int.EntityDefinition<Commune>(
        model: _entities[2],
        toOneRelations: (Commune object) => [],
        toManyRelations: (Commune object) => {},
        getId: (Commune object) => object.id,
        setId: (Commune object, int id) {
          object.id = id;
        },
        objectToFB: (Commune object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = Commune(uid: uidParam, libelle: libelleParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    CustomUser: obx_int.EntityDefinition<CustomUser>(
        model: _entities[3],
        toOneRelations: (CustomUser object) => [],
        toManyRelations: (CustomUser object) => {},
        getId: (CustomUser object) => object.id,
        setId: (CustomUser object, int id) {
          object.id = id;
        },
        objectToFB: (CustomUser object, fb.Builder fbb) {
          final firstNameOffset = object.firstName == null
              ? null
              : fbb.writeString(object.firstName!);
          final lastNameOffset = object.lastName == null
              ? null
              : fbb.writeString(object.lastName!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(2, firstNameOffset);
          fbb.addOffset(3, lastNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final firstNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final lastNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final object = CustomUser(
              id: idParam, firstName: firstNameParam, lastName: lastNameParam);

          return object;
        }),
    PointRelais: obx_int.EntityDefinition<PointRelais>(
        model: _entities[4],
        toOneRelations: (PointRelais object) => [object.type, object.commune],
        toManyRelations: (PointRelais object) => {
              obx_int.RelInfo<PointRelais>.toMany(1, object.id):
                  object.services,
              obx_int.RelInfo<PointRelais>.toMany(2, object.id):
                  object.schedules
            },
        getId: (PointRelais object) => object.id,
        setId: (PointRelais object, int id) {
          object.id = id;
        },
        objectToFB: (PointRelais object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addOffset(3, addressOffset);
          fbb.addOffset(4, descriptionOffset);
          fbb.addFloat64(5, object.latitude);
          fbb.addFloat64(6, object.longitude);
          fbb.addInt64(7, object.type.targetId);
          fbb.addInt64(8, object.commune.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final latitudeParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 14);
          final longitudeParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 16);
          final object = PointRelais(
              id: idParam,
              uid: uidParam,
              libelle: libelleParam,
              address: addressParam,
              description: descriptionParam,
              latitude: latitudeParam,
              longitude: longitudeParam);
          object.type.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.type.attach(store);
          object.commune.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.commune.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<PointRelais>(object.services,
              store, obx_int.RelInfo<PointRelais>.toMany(1, object.id));
          obx_int.InternalToManyAccess.setRelInfo<PointRelais>(object.schedules,
              store, obx_int.RelInfo<PointRelais>.toMany(2, object.id));
          return object;
        }),
    Schedule: obx_int.EntityDefinition<Schedule>(
        model: _entities[5],
        toOneRelations: (Schedule object) => [object.point_relais],
        toManyRelations: (Schedule object) => {},
        getId: (Schedule object) => object.id,
        setId: (Schedule object, int id) {
          object.id = id;
        },
        objectToFB: (Schedule object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addInt64(2, object.level_day);
          fbb.addBool(3, object.available);
          fbb.addInt64(4, object.point_relais.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final level_dayParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final availableParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final object = Schedule(
              uid: uidParam,
              level_day: level_dayParam,
              available: availableParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.point_relais.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.point_relais.attach(store);
          return object;
        }),
    StatusColis: obx_int.EntityDefinition<StatusColis>(
        model: _entities[6],
        toOneRelations: (StatusColis object) => [],
        toManyRelations: (StatusColis object) => {},
        getId: (StatusColis object) => object.id,
        setId: (StatusColis object, int id) {
          object.id = id;
        },
        objectToFB: (StatusColis object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final descriptionOffset = fbb.writeString(object.description);
          final colorOffset = fbb.writeString(object.color);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addOffset(4, colorOffset);
          fbb.addInt64(5, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final colorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = StatusColis(
              uid: uidParam,
              libelle: libelleParam,
              level: levelParam,
              description: descriptionParam,
              color: colorParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeClient: obx_int.EntityDefinition<TypeClient>(
        model: _entities[7],
        toOneRelations: (TypeClient object) => [],
        toManyRelations: (TypeClient object) => {},
        getId: (TypeClient object) => object.id,
        setId: (TypeClient object, int id) {
          object.id = id;
        },
        objectToFB: (TypeClient object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addInt64(3, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = TypeClient(
              uid: uidParam, libelle: libelleParam, level: levelParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeColis: obx_int.EntityDefinition<TypeColis>(
        model: _entities[8],
        toOneRelations: (TypeColis object) =>
            [object.emballage, object.vehicule],
        toManyRelations: (TypeColis object) => {},
        getId: (TypeColis object) => object.id,
        setId: (TypeColis object, int id) {
          object.id = id;
        },
        objectToFB: (TypeColis object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final iconeOffset = fbb.writeString(object.icone);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addInt64(3, object.level);
          fbb.addOffset(4, iconeOffset);
          fbb.addOffset(5, descriptionOffset);
          fbb.addFloat64(6, object.poids_min);
          fbb.addFloat64(7, object.poids_max);
          fbb.addInt64(8, object.price);
          fbb.addInt64(9, object.emballage.targetId);
          fbb.addInt64(10, object.vehicule.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final iconeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final poids_minParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final poids_maxParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final priceParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final object = TypeColis(
              uid: uidParam,
              libelle: libelleParam,
              level: levelParam,
              description: descriptionParam,
              icone: iconeParam,
              poids_min: poids_minParam,
              poids_max: poids_maxParam,
              price: priceParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.emballage.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.emballage.attach(store);
          object.vehicule.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          object.vehicule.attach(store);
          return object;
        }),
    TypeDestinataire: obx_int.EntityDefinition<TypeDestinataire>(
        model: _entities[9],
        toOneRelations: (TypeDestinataire object) => [],
        toManyRelations: (TypeDestinataire object) => {},
        getId: (TypeDestinataire object) => object.id,
        setId: (TypeDestinataire object, int id) {
          object.id = id;
        },
        objectToFB: (TypeDestinataire object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addInt64(4, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = TypeDestinataire(
              uid: uidParam,
              description: descriptionParam,
              libelle: libelleParam,
              level: levelParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeEmballage: obx_int.EntityDefinition<TypeEmballage>(
        model: _entities[10],
        toOneRelations: (TypeEmballage object) => [],
        toManyRelations: (TypeEmballage object) => {},
        getId: (TypeEmballage object) => object.id,
        setId: (TypeEmballage object, int id) {
          object.id = id;
        },
        objectToFB: (TypeEmballage object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addInt64(3, object.price);
          fbb.addInt64(4, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final priceParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = TypeEmballage(
              uid: uidParam,
              libelle: libelleParam,
              level: levelParam,
              price: priceParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypePointRelais: obx_int.EntityDefinition<TypePointRelais>(
        model: _entities[11],
        toOneRelations: (TypePointRelais object) => [],
        toManyRelations: (TypePointRelais object) => {},
        getId: (TypePointRelais object) => object.id,
        setId: (TypePointRelais object, int id) {
          object.id = id;
        },
        objectToFB: (TypePointRelais object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = TypePointRelais(uid: uidParam, libelle: libelleParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeService: obx_int.EntityDefinition<TypeService>(
        model: _entities[12],
        toOneRelations: (TypeService object) => [],
        toManyRelations: (TypeService object) => {},
        getId: (TypeService object) => object.id,
        setId: (TypeService object, int id) {
          object.id = id;
        },
        objectToFB: (TypeService object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = TypeService(uid: uidParam, libelle: libelleParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeVehicule: obx_int.EntityDefinition<TypeVehicule>(
        model: _entities[13],
        toOneRelations: (TypeVehicule object) => [],
        toManyRelations: (TypeVehicule object) => {},
        getId: (TypeVehicule object) => object.id,
        setId: (TypeVehicule object, int id) {
          object.id = id;
        },
        objectToFB: (TypeVehicule object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final iconeOffset = fbb.writeString(object.icone);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addOffset(3, iconeOffset);
          fbb.addInt64(4, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final iconeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = TypeVehicule(
              uid: uidParam,
              libelle: libelleParam,
              icone: iconeParam,
              level: levelParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Client] entity fields to define ObjectBox queries.
class Client_ {
  /// See [Client.id].
  static final id =
      obx.QueryIntegerProperty<Client>(_entities[0].properties[0]);

  /// See [Client.uid].
  static final uid =
      obx.QueryStringProperty<Client>(_entities[0].properties[1]);

  /// See [Client.contact].
  static final contact =
      obx.QueryStringProperty<Client>(_entities[0].properties[2]);

  /// See [Client.address].
  static final address =
      obx.QueryStringProperty<Client>(_entities[0].properties[3]);

  /// See [Client.active].
  static final active =
      obx.QueryBooleanProperty<Client>(_entities[0].properties[4]);

  /// See [Client.typeClient].
  static final typeClient =
      obx.QueryRelationToOne<Client, TypeClient>(_entities[0].properties[5]);

  /// See [Client.user].
  static final user =
      obx.QueryRelationToOne<Client, CustomUser>(_entities[0].properties[6]);
}

/// [Colis] entity fields to define ObjectBox queries.
class Colis_ {
  /// See [Colis.id].
  static final id = obx.QueryIntegerProperty<Colis>(_entities[1].properties[0]);

  /// See [Colis.uid].
  static final uid = obx.QueryStringProperty<Colis>(_entities[1].properties[1]);

  /// See [Colis.code].
  static final code =
      obx.QueryStringProperty<Colis>(_entities[1].properties[2]);

  /// See [Colis.receiverName].
  static final receiverName =
      obx.QueryStringProperty<Colis>(_entities[1].properties[3]);

  /// See [Colis.receiverPhone].
  static final receiverPhone =
      obx.QueryStringProperty<Colis>(_entities[1].properties[4]);

  /// See [Colis.total].
  static final total =
      obx.QueryIntegerProperty<Colis>(_entities[1].properties[5]);

  /// See [Colis.sender].
  static final sender =
      obx.QueryRelationToOne<Colis, Client>(_entities[1].properties[6]);

  /// See [Colis.receiver].
  static final receiver =
      obx.QueryRelationToOne<Colis, Client>(_entities[1].properties[7]);

  /// See [Colis.pointRelaisSender].
  static final pointRelaisSender =
      obx.QueryRelationToOne<Colis, PointRelais>(_entities[1].properties[8]);

  /// See [Colis.pointRelaisReceiver].
  static final pointRelaisReceiver =
      obx.QueryRelationToOne<Colis, PointRelais>(_entities[1].properties[9]);

  /// See [Colis.typeColis].
  static final typeColis =
      obx.QueryRelationToOne<Colis, TypeColis>(_entities[1].properties[10]);

  /// See [Colis.typeEmballage].
  static final typeEmballage =
      obx.QueryRelationToOne<Colis, TypeEmballage>(_entities[1].properties[11]);

  /// See [Colis.typeDestinataire].
  static final typeDestinataire =
      obx.QueryRelationToOne<Colis, TypeDestinataire>(
          _entities[1].properties[12]);

  /// See [Colis.status].
  static final status =
      obx.QueryRelationToOne<Colis, StatusColis>(_entities[1].properties[13]);

  /// See [Colis.dateCreation].
  static final dateCreation =
      obx.QueryDateProperty<Colis>(_entities[1].properties[14]);

  /// See [Colis.depotDate].
  static final depotDate =
      obx.QueryDateProperty<Colis>(_entities[1].properties[15]);

  /// See [Colis.recuperationDate].
  static final recuperationDate =
      obx.QueryDateProperty<Colis>(_entities[1].properties[16]);

  /// See [Colis.livraisonDate].
  static final livraisonDate =
      obx.QueryDateProperty<Colis>(_entities[1].properties[17]);

  /// See [Colis.retraitDate].
  static final retraitDate =
      obx.QueryDateProperty<Colis>(_entities[1].properties[18]);
}

/// [Commune] entity fields to define ObjectBox queries.
class Commune_ {
  /// See [Commune.id].
  static final id =
      obx.QueryIntegerProperty<Commune>(_entities[2].properties[0]);

  /// See [Commune.uid].
  static final uid =
      obx.QueryStringProperty<Commune>(_entities[2].properties[1]);

  /// See [Commune.libelle].
  static final libelle =
      obx.QueryStringProperty<Commune>(_entities[2].properties[2]);
}

/// [CustomUser] entity fields to define ObjectBox queries.
class CustomUser_ {
  /// See [CustomUser.id].
  static final id =
      obx.QueryIntegerProperty<CustomUser>(_entities[3].properties[0]);

  /// See [CustomUser.firstName].
  static final firstName =
      obx.QueryStringProperty<CustomUser>(_entities[3].properties[1]);

  /// See [CustomUser.lastName].
  static final lastName =
      obx.QueryStringProperty<CustomUser>(_entities[3].properties[2]);
}

/// [PointRelais] entity fields to define ObjectBox queries.
class PointRelais_ {
  /// See [PointRelais.id].
  static final id =
      obx.QueryIntegerProperty<PointRelais>(_entities[4].properties[0]);

  /// See [PointRelais.uid].
  static final uid =
      obx.QueryStringProperty<PointRelais>(_entities[4].properties[1]);

  /// See [PointRelais.libelle].
  static final libelle =
      obx.QueryStringProperty<PointRelais>(_entities[4].properties[2]);

  /// See [PointRelais.address].
  static final address =
      obx.QueryStringProperty<PointRelais>(_entities[4].properties[3]);

  /// See [PointRelais.description].
  static final description =
      obx.QueryStringProperty<PointRelais>(_entities[4].properties[4]);

  /// See [PointRelais.latitude].
  static final latitude =
      obx.QueryDoubleProperty<PointRelais>(_entities[4].properties[5]);

  /// See [PointRelais.longitude].
  static final longitude =
      obx.QueryDoubleProperty<PointRelais>(_entities[4].properties[6]);

  /// See [PointRelais.type].
  static final type = obx.QueryRelationToOne<PointRelais, TypePointRelais>(
      _entities[4].properties[7]);

  /// See [PointRelais.commune].
  static final commune =
      obx.QueryRelationToOne<PointRelais, Commune>(_entities[4].properties[8]);

  /// see [PointRelais.services]
  static final services = obx.QueryRelationToMany<PointRelais, TypeService>(
      _entities[4].relations[0]);

  /// see [PointRelais.schedules]
  static final schedules =
      obx.QueryRelationToMany<PointRelais, Schedule>(_entities[4].relations[1]);
}

/// [Schedule] entity fields to define ObjectBox queries.
class Schedule_ {
  /// See [Schedule.id].
  static final id =
      obx.QueryIntegerProperty<Schedule>(_entities[5].properties[0]);

  /// See [Schedule.uid].
  static final uid =
      obx.QueryStringProperty<Schedule>(_entities[5].properties[1]);

  /// See [Schedule.level_day].
  static final level_day =
      obx.QueryIntegerProperty<Schedule>(_entities[5].properties[2]);

  /// See [Schedule.available].
  static final available =
      obx.QueryBooleanProperty<Schedule>(_entities[5].properties[3]);

  /// See [Schedule.point_relais].
  static final point_relais =
      obx.QueryRelationToOne<Schedule, PointRelais>(_entities[5].properties[4]);
}

/// [StatusColis] entity fields to define ObjectBox queries.
class StatusColis_ {
  /// See [StatusColis.id].
  static final id =
      obx.QueryIntegerProperty<StatusColis>(_entities[6].properties[0]);

  /// See [StatusColis.uid].
  static final uid =
      obx.QueryStringProperty<StatusColis>(_entities[6].properties[1]);

  /// See [StatusColis.libelle].
  static final libelle =
      obx.QueryStringProperty<StatusColis>(_entities[6].properties[2]);

  /// See [StatusColis.description].
  static final description =
      obx.QueryStringProperty<StatusColis>(_entities[6].properties[3]);

  /// See [StatusColis.color].
  static final color =
      obx.QueryStringProperty<StatusColis>(_entities[6].properties[4]);

  /// See [StatusColis.level].
  static final level =
      obx.QueryIntegerProperty<StatusColis>(_entities[6].properties[5]);
}

/// [TypeClient] entity fields to define ObjectBox queries.
class TypeClient_ {
  /// See [TypeClient.id].
  static final id =
      obx.QueryIntegerProperty<TypeClient>(_entities[7].properties[0]);

  /// See [TypeClient.uid].
  static final uid =
      obx.QueryStringProperty<TypeClient>(_entities[7].properties[1]);

  /// See [TypeClient.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeClient>(_entities[7].properties[2]);

  /// See [TypeClient.level].
  static final level =
      obx.QueryIntegerProperty<TypeClient>(_entities[7].properties[3]);
}

/// [TypeColis] entity fields to define ObjectBox queries.
class TypeColis_ {
  /// See [TypeColis.id].
  static final id =
      obx.QueryIntegerProperty<TypeColis>(_entities[8].properties[0]);

  /// See [TypeColis.uid].
  static final uid =
      obx.QueryStringProperty<TypeColis>(_entities[8].properties[1]);

  /// See [TypeColis.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeColis>(_entities[8].properties[2]);

  /// See [TypeColis.level].
  static final level =
      obx.QueryIntegerProperty<TypeColis>(_entities[8].properties[3]);

  /// See [TypeColis.icone].
  static final icone =
      obx.QueryStringProperty<TypeColis>(_entities[8].properties[4]);

  /// See [TypeColis.description].
  static final description =
      obx.QueryStringProperty<TypeColis>(_entities[8].properties[5]);

  /// See [TypeColis.poids_min].
  static final poids_min =
      obx.QueryDoubleProperty<TypeColis>(_entities[8].properties[6]);

  /// See [TypeColis.poids_max].
  static final poids_max =
      obx.QueryDoubleProperty<TypeColis>(_entities[8].properties[7]);

  /// See [TypeColis.price].
  static final price =
      obx.QueryIntegerProperty<TypeColis>(_entities[8].properties[8]);

  /// See [TypeColis.emballage].
  static final emballage = obx.QueryRelationToOne<TypeColis, TypeEmballage>(
      _entities[8].properties[9]);

  /// See [TypeColis.vehicule].
  static final vehicule = obx.QueryRelationToOne<TypeColis, TypeVehicule>(
      _entities[8].properties[10]);
}

/// [TypeDestinataire] entity fields to define ObjectBox queries.
class TypeDestinataire_ {
  /// See [TypeDestinataire.id].
  static final id =
      obx.QueryIntegerProperty<TypeDestinataire>(_entities[9].properties[0]);

  /// See [TypeDestinataire.uid].
  static final uid =
      obx.QueryStringProperty<TypeDestinataire>(_entities[9].properties[1]);

  /// See [TypeDestinataire.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeDestinataire>(_entities[9].properties[2]);

  /// See [TypeDestinataire.description].
  static final description =
      obx.QueryStringProperty<TypeDestinataire>(_entities[9].properties[3]);

  /// See [TypeDestinataire.level].
  static final level =
      obx.QueryIntegerProperty<TypeDestinataire>(_entities[9].properties[4]);
}

/// [TypeEmballage] entity fields to define ObjectBox queries.
class TypeEmballage_ {
  /// See [TypeEmballage.id].
  static final id =
      obx.QueryIntegerProperty<TypeEmballage>(_entities[10].properties[0]);

  /// See [TypeEmballage.uid].
  static final uid =
      obx.QueryStringProperty<TypeEmballage>(_entities[10].properties[1]);

  /// See [TypeEmballage.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeEmballage>(_entities[10].properties[2]);

  /// See [TypeEmballage.price].
  static final price =
      obx.QueryIntegerProperty<TypeEmballage>(_entities[10].properties[3]);

  /// See [TypeEmballage.level].
  static final level =
      obx.QueryIntegerProperty<TypeEmballage>(_entities[10].properties[4]);
}

/// [TypePointRelais] entity fields to define ObjectBox queries.
class TypePointRelais_ {
  /// See [TypePointRelais.id].
  static final id =
      obx.QueryIntegerProperty<TypePointRelais>(_entities[11].properties[0]);

  /// See [TypePointRelais.uid].
  static final uid =
      obx.QueryStringProperty<TypePointRelais>(_entities[11].properties[1]);

  /// See [TypePointRelais.libelle].
  static final libelle =
      obx.QueryStringProperty<TypePointRelais>(_entities[11].properties[2]);
}

/// [TypeService] entity fields to define ObjectBox queries.
class TypeService_ {
  /// See [TypeService.id].
  static final id =
      obx.QueryIntegerProperty<TypeService>(_entities[12].properties[0]);

  /// See [TypeService.uid].
  static final uid =
      obx.QueryStringProperty<TypeService>(_entities[12].properties[1]);

  /// See [TypeService.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeService>(_entities[12].properties[2]);
}

/// [TypeVehicule] entity fields to define ObjectBox queries.
class TypeVehicule_ {
  /// See [TypeVehicule.id].
  static final id =
      obx.QueryIntegerProperty<TypeVehicule>(_entities[13].properties[0]);

  /// See [TypeVehicule.uid].
  static final uid =
      obx.QueryStringProperty<TypeVehicule>(_entities[13].properties[1]);

  /// See [TypeVehicule.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeVehicule>(_entities[13].properties[2]);

  /// See [TypeVehicule.icone].
  static final icone =
      obx.QueryStringProperty<TypeVehicule>(_entities[13].properties[3]);

  /// See [TypeVehicule.level].
  static final level =
      obx.QueryIntegerProperty<TypeVehicule>(_entities[13].properties[4]);
}
