// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/AdministrationApp/CustomUser.dart';
import 'models/ClientApp/Client.dart';
import 'models/ClientApp/NotificationClient.dart';
import 'models/ClientApp/PalierClient.dart';
import 'models/ClientApp/TypeClient.dart';
import 'models/ColisApp/Colis.dart';
import 'models/ColisApp/StatusColis.dart';
import 'models/ColisApp/TypeColis.dart';
import 'models/ColisApp/TypeDestinataire.dart';
import 'models/ColisApp/TypeEmballage.dart';
import 'models/LivraisonApp/TypeVehicule.dart';
import 'models/PointRelaisApp/PointRelais.dart';
import 'models/PointRelaisApp/Schedule.dart';
import 'models/PointRelaisApp/TypePointRelais.dart';
import 'models/PointRelaisApp/TypeService.dart';
import 'models/ZoneApp/Commune.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5518771513760433252),
      name: 'Client',
      lastPropertyId: const obx_int.IdUid(8, 5218986931365160862),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 9186364488723110502),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2875610646821227067),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 5245307889289555106)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3660305949257334503),
            name: 'contact',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 108084052903366684),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3002779939758054398),
            name: 'active',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4346612026937696375),
            name: 'typeClientId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 8967728281504295153),
            relationTarget: 'TypeClient'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7032582005422917576),
            name: 'userId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 2336354479783538388),
            relationTarget: 'CustomUser'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5218986931365160862),
            name: 'palierId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 4003714850913850968),
            relationTarget: 'PalierClient')
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 4362593878124396942),
            name: 'notifications',
            targetId: const obx_int.IdUid(5, 1951383446368822470))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 3543005446155189019),
      name: 'Colis',
      lastPropertyId: const obx_int.IdUid(22, 5931844170898409852),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8661980573674310907),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 938160887724095996),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(5, 3445501522734864135)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5729826661462420546),
            name: 'code',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2490487003591671175),
            name: 'receiverName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8129364307271409881),
            name: 'receiverPhone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4819391443040149680),
            name: 'total',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1232551263455015295),
            name: 'senderId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(6, 4291832831043614495),
            relationTarget: 'Client'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3640045915888110745),
            name: 'receiverId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(7, 2222931194962019945),
            relationTarget: 'Client'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6766421742162155855),
            name: 'pointRelaisSenderId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(8, 2726959951927083560),
            relationTarget: 'PointRelais'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6122331589877278671),
            name: 'pointRelaisReceiverId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(9, 4542294666478747493),
            relationTarget: 'PointRelais'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 6301148791039575650),
            name: 'typeColisId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(10, 6776622867264763626),
            relationTarget: 'TypeColis'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3894922596764913500),
            name: 'typeEmballageId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(11, 5937384142616592552),
            relationTarget: 'TypeEmballage'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 8041217857504485802),
            name: 'typeDestinataireId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(12, 8801557170822615330),
            relationTarget: 'TypeDestinataire'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 2071480972610544286),
            name: 'statusId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(13, 2807872355433489923),
            relationTarget: 'StatusColis'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 7778899611050487091),
            name: 'dateCreation',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 437991993152677718),
            name: 'depotDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 7982282030157446035),
            name: 'recuperationDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 3506877785330752144),
            name: 'livraisonDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 8411599506013840631),
            name: 'retraitDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 3313579533878786326),
            name: 'sold',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 5931844170898409852),
            name: 'startToPayement',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 4992535986533297587),
      name: 'Commune',
      lastPropertyId: const obx_int.IdUid(3, 1502124290931998554),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7980700817362763664),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3078064505712908328),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(14, 7101812368353549488)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1502124290931998554),
            name: 'libelle',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 3437007084483648727),
      name: 'CustomUser',
      lastPropertyId: const obx_int.IdUid(4, 1178120999567415230),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1598687141462235503),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7073403030105897970),
            name: 'firstName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8697899709503104142),
            name: 'lastName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1178120999567415230),
            name: 'fcmtoken',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 1951383446368822470),
      name: 'NotificationClient',
      lastPropertyId: const obx_int.IdUid(7, 3921310296109265394),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5351889466850277692),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4369461125528308041),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(15, 4280499006352540613)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4787714140432165502),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2234512909278112095),
            name: 'read',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7539174481721758238),
            name: 'message',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3917335003876633041),
            name: 'priority',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3921310296109265394),
            name: 'date_creation',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 25261470569710999),
      name: 'PalierClient',
      lastPropertyId: const obx_int.IdUid(5, 281757582351663685),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2639933439217612760),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3782462349004564333),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(16, 7902688073560596718)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5279717264357062291),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 971439013872996953),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 281757582351663685),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 6970987695869343513),
      name: 'PointRelais',
      lastPropertyId: const obx_int.IdUid(9, 4818371208172813927),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6539481632965241056),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1702320748304105824),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(17, 271197234340355534)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3801996390814348445),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 9120317290868995219),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1880384771155734665),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4218858410819805397),
            name: 'latitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5931861662624371425),
            name: 'longitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 9060572880269633279),
            name: 'typeId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(18, 1469981824518002391),
            relationTarget: 'TypePointRelais'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4818371208172813927),
            name: 'communeId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(19, 5165418151463275286),
            relationTarget: 'Commune')
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(2, 193642714595025303),
            name: 'services',
            targetId: const obx_int.IdUid(15, 5172060657342811275)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(3, 2517163978363044878),
            name: 'schedules',
            targetId: const obx_int.IdUid(8, 2963682808090904853))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 2963682808090904853),
      name: 'Schedule',
      lastPropertyId: const obx_int.IdUid(7, 1406712626477052109),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7018933445435719359),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3817702474835878543),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(20, 5947405641441282949)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2852929405550632496),
            name: 'level_day',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7308239954928171679),
            name: 'available',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2370905921784491829),
            name: 'point_relaisId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(21, 1264718184553367279),
            relationTarget: 'PointRelais'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7998669130440192038),
            name: 'startHour',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1406712626477052109),
            name: 'endHour',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 8439786241858360762),
      name: 'StatusColis',
      lastPropertyId: const obx_int.IdUid(6, 5548855459900953752),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5107058979102204299),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3968829971953422838),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(22, 3843760215456606924)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 903947182572976791),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7395840806617215544),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 458472111317189195),
            name: 'color',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5548855459900953752),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(10, 3089692671208744379),
      name: 'TypeClient',
      lastPropertyId: const obx_int.IdUid(4, 7251628959274605606),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4918872237823965691),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8566433462815727569),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(23, 1590839508952707524)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4759817217067453952),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7251628959274605606),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(11, 7072311278531203013),
      name: 'TypeColis',
      lastPropertyId: const obx_int.IdUid(11, 7325081203132247470),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2988644549531870771),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4873311037540481756),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(24, 4364206024413008605)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3844992426791797646),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1292697485738997695),
            name: 'level',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1897535432980255144),
            name: 'icone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3494015666377326949),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8998903113228638593),
            name: 'poids_min',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7994600289133079365),
            name: 'poids_max',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 968426915803892449),
            name: 'price',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5560959173062560501),
            name: 'emballageId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(25, 2411599155623618619),
            relationTarget: 'TypeEmballage'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 7325081203132247470),
            name: 'vehiculeId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(26, 900745232223966810),
            relationTarget: 'TypeVehicule')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(12, 7883760003877131682),
      name: 'TypeDestinataire',
      lastPropertyId: const obx_int.IdUid(5, 929596019534864895),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4097401318073434771),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7773413216020354872),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(27, 1411798440803324629)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8673003740915386777),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4916146294514257567),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 929596019534864895),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(13, 6291509022590950744),
      name: 'TypeEmballage',
      lastPropertyId: const obx_int.IdUid(5, 8294897350387810440),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6052891580703704615),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4887823237696537257),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(28, 8628644023611341212)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3205198230620173017),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8504604742699137845),
            name: 'price',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8294897350387810440),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(14, 8631890454663572794),
      name: 'TypePointRelais',
      lastPropertyId: const obx_int.IdUid(3, 3677105239584672192),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1422123930174755942),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3692334326746180256),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(29, 3738412890561809686)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3677105239584672192),
            name: 'libelle',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(15, 5172060657342811275),
      name: 'TypeService',
      lastPropertyId: const obx_int.IdUid(3, 2368085543694315926),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6401604663223468196),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7865217358164780980),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(30, 362561778898777772)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2368085543694315926),
            name: 'libelle',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(16, 7330747115985110482),
      name: 'TypeVehicule',
      lastPropertyId: const obx_int.IdUid(5, 489780662833049686),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3208100503313732416),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8191078175999151866),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(31, 7633977393871195353)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3323057709637294836),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7340424179110944503),
            name: 'icone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 489780662833049686),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(16, 7330747115985110482),
      lastIndexId: const obx_int.IdUid(31, 7633977393871195353),
      lastRelationId: const obx_int.IdUid(3, 2517163978363044878),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [7792046605721729129],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Client: obx_int.EntityDefinition<Client>(
        model: _entities[0],
        toOneRelations: (Client object) =>
            [object.typeClient, object.user, object.palier],
        toManyRelations: (Client object) => {
              obx_int.RelInfo<Client>.toMany(1, object.id): object.notifications
            },
        getId: (Client object) => object.id,
        setId: (Client object, int id) {
          object.id = id;
        },
        objectToFB: (Client object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final contactOffset = fbb.writeString(object.contact);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, contactOffset);
          fbb.addOffset(3, addressOffset);
          fbb.addBool(4, object.active);
          fbb.addInt64(5, object.typeClient.targetId);
          fbb.addInt64(6, object.user.targetId);
          fbb.addInt64(7, object.palier.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final contactParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final activeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final object = Client(
              uid: uidParam,
              contact: contactParam,
              address: addressParam,
              active: activeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.typeClient.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.typeClient.attach(store);
          object.user.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.user.attach(store);
          object.palier.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.palier.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Client>(object.notifications,
              store, obx_int.RelInfo<Client>.toMany(1, object.id));
          return object;
        }),
    Colis: obx_int.EntityDefinition<Colis>(
        model: _entities[1],
        toOneRelations: (Colis object) => [
              object.sender,
              object.receiver,
              object.pointRelaisSender,
              object.pointRelaisReceiver,
              object.typeColis,
              object.typeEmballage,
              object.typeDestinataire,
              object.status
            ],
        toManyRelations: (Colis object) => {},
        getId: (Colis object) => object.id,
        setId: (Colis object, int id) {
          object.id = id;
        },
        objectToFB: (Colis object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final codeOffset = fbb.writeString(object.code);
          final receiverNameOffset = fbb.writeString(object.receiverName);
          final receiverPhoneOffset = fbb.writeString(object.receiverPhone);
          fbb.startTable(23);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, codeOffset);
          fbb.addOffset(3, receiverNameOffset);
          fbb.addOffset(4, receiverPhoneOffset);
          fbb.addInt64(5, object.total);
          fbb.addInt64(6, object.sender.targetId);
          fbb.addInt64(7, object.receiver.targetId);
          fbb.addInt64(8, object.pointRelaisSender.targetId);
          fbb.addInt64(9, object.pointRelaisReceiver.targetId);
          fbb.addInt64(10, object.typeColis.targetId);
          fbb.addInt64(11, object.typeEmballage.targetId);
          fbb.addInt64(12, object.typeDestinataire.targetId);
          fbb.addInt64(13, object.status.targetId);
          fbb.addInt64(14, object.dateCreation?.millisecondsSinceEpoch);
          fbb.addInt64(15, object.depotDate?.millisecondsSinceEpoch);
          fbb.addInt64(16, object.recuperationDate?.millisecondsSinceEpoch);
          fbb.addInt64(17, object.livraisonDate?.millisecondsSinceEpoch);
          fbb.addInt64(18, object.retraitDate?.millisecondsSinceEpoch);
          fbb.addBool(19, object.sold);
          fbb.addBool(21, object.startToPayement);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateCreationValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 32);
          final depotDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 34);
          final recuperationDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 36);
          final livraisonDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 38);
          final retraitDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 40);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final codeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final receiverNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final receiverPhoneParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final totalParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final soldParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 42, false);
          final startToPayementParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 46, false);
          final depotDateParam = depotDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(depotDateValue);
          final recuperationDateParam = recuperationDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(recuperationDateValue);
          final livraisonDateParam = livraisonDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(livraisonDateValue);
          final retraitDateParam = retraitDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(retraitDateValue);
          final dateCreationParam = dateCreationValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dateCreationValue);
          final object = Colis(
              id: idParam,
              uid: uidParam,
              code: codeParam,
              receiverName: receiverNameParam,
              receiverPhone: receiverPhoneParam,
              total: totalParam,
              sold: soldParam,
              startToPayement: startToPayementParam,
              depotDate: depotDateParam,
              recuperationDate: recuperationDateParam,
              livraisonDate: livraisonDateParam,
              retraitDate: retraitDateParam,
              dateCreation: dateCreationParam);
          object.sender.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.sender.attach(store);
          object.receiver.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.receiver.attach(store);
          object.pointRelaisSender.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.pointRelaisSender.attach(store);
          object.pointRelaisReceiver.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.pointRelaisReceiver.attach(store);
          object.typeColis.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          object.typeColis.attach(store);
          object.typeEmballage.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          object.typeEmballage.attach(store);
          object.typeDestinataire.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          object.typeDestinataire.attach(store);
          object.status.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0);
          object.status.attach(store);
          return object;
        }),
    Commune: obx_int.EntityDefinition<Commune>(
        model: _entities[2],
        toOneRelations: (Commune object) => [],
        toManyRelations: (Commune object) => {},
        getId: (Commune object) => object.id,
        setId: (Commune object, int id) {
          object.id = id;
        },
        objectToFB: (Commune object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = Commune(uid: uidParam, libelle: libelleParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    CustomUser: obx_int.EntityDefinition<CustomUser>(
        model: _entities[3],
        toOneRelations: (CustomUser object) => [],
        toManyRelations: (CustomUser object) => {},
        getId: (CustomUser object) => object.id,
        setId: (CustomUser object, int id) {
          object.id = id;
        },
        objectToFB: (CustomUser object, fb.Builder fbb) {
          final firstNameOffset = object.firstName == null
              ? null
              : fbb.writeString(object.firstName!);
          final lastNameOffset = object.lastName == null
              ? null
              : fbb.writeString(object.lastName!);
          final fcmtokenOffset = object.fcmtoken == null
              ? null
              : fbb.writeString(object.fcmtoken!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, firstNameOffset);
          fbb.addOffset(2, lastNameOffset);
          fbb.addOffset(3, fcmtokenOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final firstNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final lastNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final fcmtokenParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final object = CustomUser(
              id: idParam,
              firstName: firstNameParam,
              lastName: lastNameParam,
              fcmtoken: fcmtokenParam);

          return object;
        }),
    NotificationClient: obx_int.EntityDefinition<NotificationClient>(
        model: _entities[4],
        toOneRelations: (NotificationClient object) => [],
        toManyRelations: (NotificationClient object) => {},
        getId: (NotificationClient object) => object.id,
        setId: (NotificationClient object, int id) {
          object.id = id;
        },
        objectToFB: (NotificationClient object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final titleOffset = fbb.writeString(object.title);
          final messageOffset = fbb.writeString(object.message);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addBool(3, object.read);
          fbb.addOffset(4, messageOffset);
          fbb.addBool(5, object.priority);
          fbb.addInt64(6, object.date_creation?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final date_creationValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final readParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final messageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final priorityParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final date_creationParam = date_creationValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(date_creationValue);
          final object = NotificationClient(
              uid: uidParam,
              title: titleParam,
              read: readParam,
              message: messageParam,
              priority: priorityParam,
              date_creation: date_creationParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    PalierClient: obx_int.EntityDefinition<PalierClient>(
        model: _entities[5],
        toOneRelations: (PalierClient object) => [],
        toManyRelations: (PalierClient object) => {},
        getId: (PalierClient object) => object.id,
        setId: (PalierClient object, int id) {
          object.id = id;
        },
        objectToFB: (PalierClient object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addInt64(4, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = PalierClient(
              uid: uidParam,
              libelle: libelleParam,
              description: descriptionParam,
              level: levelParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    PointRelais: obx_int.EntityDefinition<PointRelais>(
        model: _entities[6],
        toOneRelations: (PointRelais object) => [object.type, object.commune],
        toManyRelations: (PointRelais object) => {
              obx_int.RelInfo<PointRelais>.toMany(2, object.id):
                  object.services,
              obx_int.RelInfo<PointRelais>.toMany(3, object.id):
                  object.schedules
            },
        getId: (PointRelais object) => object.id,
        setId: (PointRelais object, int id) {
          object.id = id;
        },
        objectToFB: (PointRelais object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addOffset(3, addressOffset);
          fbb.addOffset(4, descriptionOffset);
          fbb.addFloat64(5, object.latitude);
          fbb.addFloat64(6, object.longitude);
          fbb.addInt64(7, object.type.targetId);
          fbb.addInt64(8, object.commune.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final latitudeParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 14);
          final longitudeParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 16);
          final object = PointRelais(
              id: idParam,
              uid: uidParam,
              libelle: libelleParam,
              address: addressParam,
              description: descriptionParam,
              latitude: latitudeParam,
              longitude: longitudeParam);
          object.type.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.type.attach(store);
          object.commune.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.commune.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<PointRelais>(object.services,
              store, obx_int.RelInfo<PointRelais>.toMany(2, object.id));
          obx_int.InternalToManyAccess.setRelInfo<PointRelais>(object.schedules,
              store, obx_int.RelInfo<PointRelais>.toMany(3, object.id));
          return object;
        }),
    Schedule: obx_int.EntityDefinition<Schedule>(
        model: _entities[7],
        toOneRelations: (Schedule object) => [object.point_relais],
        toManyRelations: (Schedule object) => {},
        getId: (Schedule object) => object.id,
        setId: (Schedule object, int id) {
          object.id = id;
        },
        objectToFB: (Schedule object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final startHourOffset = object.startHour == null
              ? null
              : fbb.writeString(object.startHour!);
          final endHourOffset =
              object.endHour == null ? null : fbb.writeString(object.endHour!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addInt64(2, object.level_day);
          fbb.addBool(3, object.available);
          fbb.addInt64(4, object.point_relais.targetId);
          fbb.addOffset(5, startHourOffset);
          fbb.addOffset(6, endHourOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final level_dayParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final availableParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final startHourParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final endHourParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final object = Schedule(
              uid: uidParam,
              level_day: level_dayParam,
              available: availableParam,
              startHour: startHourParam,
              endHour: endHourParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.point_relais.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.point_relais.attach(store);
          return object;
        }),
    StatusColis: obx_int.EntityDefinition<StatusColis>(
        model: _entities[8],
        toOneRelations: (StatusColis object) => [],
        toManyRelations: (StatusColis object) => {},
        getId: (StatusColis object) => object.id,
        setId: (StatusColis object, int id) {
          object.id = id;
        },
        objectToFB: (StatusColis object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final descriptionOffset = fbb.writeString(object.description);
          final colorOffset = fbb.writeString(object.color);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addOffset(4, colorOffset);
          fbb.addInt64(5, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final colorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = StatusColis(
              uid: uidParam,
              libelle: libelleParam,
              level: levelParam,
              description: descriptionParam,
              color: colorParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeClient: obx_int.EntityDefinition<TypeClient>(
        model: _entities[9],
        toOneRelations: (TypeClient object) => [],
        toManyRelations: (TypeClient object) => {},
        getId: (TypeClient object) => object.id,
        setId: (TypeClient object, int id) {
          object.id = id;
        },
        objectToFB: (TypeClient object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addInt64(3, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = TypeClient(
              uid: uidParam, libelle: libelleParam, level: levelParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeColis: obx_int.EntityDefinition<TypeColis>(
        model: _entities[10],
        toOneRelations: (TypeColis object) =>
            [object.emballage, object.vehicule],
        toManyRelations: (TypeColis object) => {},
        getId: (TypeColis object) => object.id,
        setId: (TypeColis object, int id) {
          object.id = id;
        },
        objectToFB: (TypeColis object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final iconeOffset = fbb.writeString(object.icone);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addInt64(3, object.level);
          fbb.addOffset(4, iconeOffset);
          fbb.addOffset(5, descriptionOffset);
          fbb.addFloat64(6, object.poids_min);
          fbb.addFloat64(7, object.poids_max);
          fbb.addInt64(8, object.price);
          fbb.addInt64(9, object.emballage.targetId);
          fbb.addInt64(10, object.vehicule.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final iconeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final poids_minParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final poids_maxParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final priceParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final object = TypeColis(
              uid: uidParam,
              libelle: libelleParam,
              level: levelParam,
              description: descriptionParam,
              icone: iconeParam,
              poids_min: poids_minParam,
              poids_max: poids_maxParam,
              price: priceParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.emballage.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.emballage.attach(store);
          object.vehicule.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          object.vehicule.attach(store);
          return object;
        }),
    TypeDestinataire: obx_int.EntityDefinition<TypeDestinataire>(
        model: _entities[11],
        toOneRelations: (TypeDestinataire object) => [],
        toManyRelations: (TypeDestinataire object) => {},
        getId: (TypeDestinataire object) => object.id,
        setId: (TypeDestinataire object, int id) {
          object.id = id;
        },
        objectToFB: (TypeDestinataire object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addInt64(4, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = TypeDestinataire(
              uid: uidParam,
              description: descriptionParam,
              libelle: libelleParam,
              level: levelParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeEmballage: obx_int.EntityDefinition<TypeEmballage>(
        model: _entities[12],
        toOneRelations: (TypeEmballage object) => [],
        toManyRelations: (TypeEmballage object) => {},
        getId: (TypeEmballage object) => object.id,
        setId: (TypeEmballage object, int id) {
          object.id = id;
        },
        objectToFB: (TypeEmballage object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addInt64(3, object.price);
          fbb.addInt64(4, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final priceParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = TypeEmballage(
              uid: uidParam,
              libelle: libelleParam,
              level: levelParam,
              price: priceParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypePointRelais: obx_int.EntityDefinition<TypePointRelais>(
        model: _entities[13],
        toOneRelations: (TypePointRelais object) => [],
        toManyRelations: (TypePointRelais object) => {},
        getId: (TypePointRelais object) => object.id,
        setId: (TypePointRelais object, int id) {
          object.id = id;
        },
        objectToFB: (TypePointRelais object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = TypePointRelais(uid: uidParam, libelle: libelleParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeService: obx_int.EntityDefinition<TypeService>(
        model: _entities[14],
        toOneRelations: (TypeService object) => [],
        toManyRelations: (TypeService object) => {},
        getId: (TypeService object) => object.id,
        setId: (TypeService object, int id) {
          object.id = id;
        },
        objectToFB: (TypeService object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = TypeService(uid: uidParam, libelle: libelleParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeVehicule: obx_int.EntityDefinition<TypeVehicule>(
        model: _entities[15],
        toOneRelations: (TypeVehicule object) => [],
        toManyRelations: (TypeVehicule object) => {},
        getId: (TypeVehicule object) => object.id,
        setId: (TypeVehicule object, int id) {
          object.id = id;
        },
        objectToFB: (TypeVehicule object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          final iconeOffset = fbb.writeString(object.icone);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addOffset(3, iconeOffset);
          fbb.addInt64(4, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final iconeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = TypeVehicule(
              uid: uidParam,
              libelle: libelleParam,
              icone: iconeParam,
              level: levelParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Client] entity fields to define ObjectBox queries.
class Client_ {
  /// See [Client.id].
  static final id =
      obx.QueryIntegerProperty<Client>(_entities[0].properties[0]);

  /// See [Client.uid].
  static final uid =
      obx.QueryStringProperty<Client>(_entities[0].properties[1]);

  /// See [Client.contact].
  static final contact =
      obx.QueryStringProperty<Client>(_entities[0].properties[2]);

  /// See [Client.address].
  static final address =
      obx.QueryStringProperty<Client>(_entities[0].properties[3]);

  /// See [Client.active].
  static final active =
      obx.QueryBooleanProperty<Client>(_entities[0].properties[4]);

  /// See [Client.typeClient].
  static final typeClient =
      obx.QueryRelationToOne<Client, TypeClient>(_entities[0].properties[5]);

  /// See [Client.user].
  static final user =
      obx.QueryRelationToOne<Client, CustomUser>(_entities[0].properties[6]);

  /// See [Client.palier].
  static final palier =
      obx.QueryRelationToOne<Client, PalierClient>(_entities[0].properties[7]);

  /// see [Client.notifications]
  static final notifications =
      obx.QueryRelationToMany<Client, NotificationClient>(
          _entities[0].relations[0]);
}

/// [Colis] entity fields to define ObjectBox queries.
class Colis_ {
  /// See [Colis.id].
  static final id = obx.QueryIntegerProperty<Colis>(_entities[1].properties[0]);

  /// See [Colis.uid].
  static final uid = obx.QueryStringProperty<Colis>(_entities[1].properties[1]);

  /// See [Colis.code].
  static final code =
      obx.QueryStringProperty<Colis>(_entities[1].properties[2]);

  /// See [Colis.receiverName].
  static final receiverName =
      obx.QueryStringProperty<Colis>(_entities[1].properties[3]);

  /// See [Colis.receiverPhone].
  static final receiverPhone =
      obx.QueryStringProperty<Colis>(_entities[1].properties[4]);

  /// See [Colis.total].
  static final total =
      obx.QueryIntegerProperty<Colis>(_entities[1].properties[5]);

  /// See [Colis.sender].
  static final sender =
      obx.QueryRelationToOne<Colis, Client>(_entities[1].properties[6]);

  /// See [Colis.receiver].
  static final receiver =
      obx.QueryRelationToOne<Colis, Client>(_entities[1].properties[7]);

  /// See [Colis.pointRelaisSender].
  static final pointRelaisSender =
      obx.QueryRelationToOne<Colis, PointRelais>(_entities[1].properties[8]);

  /// See [Colis.pointRelaisReceiver].
  static final pointRelaisReceiver =
      obx.QueryRelationToOne<Colis, PointRelais>(_entities[1].properties[9]);

  /// See [Colis.typeColis].
  static final typeColis =
      obx.QueryRelationToOne<Colis, TypeColis>(_entities[1].properties[10]);

  /// See [Colis.typeEmballage].
  static final typeEmballage =
      obx.QueryRelationToOne<Colis, TypeEmballage>(_entities[1].properties[11]);

  /// See [Colis.typeDestinataire].
  static final typeDestinataire =
      obx.QueryRelationToOne<Colis, TypeDestinataire>(
          _entities[1].properties[12]);

  /// See [Colis.status].
  static final status =
      obx.QueryRelationToOne<Colis, StatusColis>(_entities[1].properties[13]);

  /// See [Colis.dateCreation].
  static final dateCreation =
      obx.QueryDateProperty<Colis>(_entities[1].properties[14]);

  /// See [Colis.depotDate].
  static final depotDate =
      obx.QueryDateProperty<Colis>(_entities[1].properties[15]);

  /// See [Colis.recuperationDate].
  static final recuperationDate =
      obx.QueryDateProperty<Colis>(_entities[1].properties[16]);

  /// See [Colis.livraisonDate].
  static final livraisonDate =
      obx.QueryDateProperty<Colis>(_entities[1].properties[17]);

  /// See [Colis.retraitDate].
  static final retraitDate =
      obx.QueryDateProperty<Colis>(_entities[1].properties[18]);

  /// See [Colis.sold].
  static final sold =
      obx.QueryBooleanProperty<Colis>(_entities[1].properties[19]);

  /// See [Colis.startToPayement].
  static final startToPayement =
      obx.QueryBooleanProperty<Colis>(_entities[1].properties[20]);
}

/// [Commune] entity fields to define ObjectBox queries.
class Commune_ {
  /// See [Commune.id].
  static final id =
      obx.QueryIntegerProperty<Commune>(_entities[2].properties[0]);

  /// See [Commune.uid].
  static final uid =
      obx.QueryStringProperty<Commune>(_entities[2].properties[1]);

  /// See [Commune.libelle].
  static final libelle =
      obx.QueryStringProperty<Commune>(_entities[2].properties[2]);
}

/// [CustomUser] entity fields to define ObjectBox queries.
class CustomUser_ {
  /// See [CustomUser.id].
  static final id =
      obx.QueryIntegerProperty<CustomUser>(_entities[3].properties[0]);

  /// See [CustomUser.firstName].
  static final firstName =
      obx.QueryStringProperty<CustomUser>(_entities[3].properties[1]);

  /// See [CustomUser.lastName].
  static final lastName =
      obx.QueryStringProperty<CustomUser>(_entities[3].properties[2]);

  /// See [CustomUser.fcmtoken].
  static final fcmtoken =
      obx.QueryStringProperty<CustomUser>(_entities[3].properties[3]);
}

/// [NotificationClient] entity fields to define ObjectBox queries.
class NotificationClient_ {
  /// See [NotificationClient.id].
  static final id =
      obx.QueryIntegerProperty<NotificationClient>(_entities[4].properties[0]);

  /// See [NotificationClient.uid].
  static final uid =
      obx.QueryStringProperty<NotificationClient>(_entities[4].properties[1]);

  /// See [NotificationClient.title].
  static final title =
      obx.QueryStringProperty<NotificationClient>(_entities[4].properties[2]);

  /// See [NotificationClient.read].
  static final read =
      obx.QueryBooleanProperty<NotificationClient>(_entities[4].properties[3]);

  /// See [NotificationClient.message].
  static final message =
      obx.QueryStringProperty<NotificationClient>(_entities[4].properties[4]);

  /// See [NotificationClient.priority].
  static final priority =
      obx.QueryBooleanProperty<NotificationClient>(_entities[4].properties[5]);

  /// See [NotificationClient.date_creation].
  static final date_creation =
      obx.QueryDateProperty<NotificationClient>(_entities[4].properties[6]);
}

/// [PalierClient] entity fields to define ObjectBox queries.
class PalierClient_ {
  /// See [PalierClient.id].
  static final id =
      obx.QueryIntegerProperty<PalierClient>(_entities[5].properties[0]);

  /// See [PalierClient.uid].
  static final uid =
      obx.QueryStringProperty<PalierClient>(_entities[5].properties[1]);

  /// See [PalierClient.libelle].
  static final libelle =
      obx.QueryStringProperty<PalierClient>(_entities[5].properties[2]);

  /// See [PalierClient.description].
  static final description =
      obx.QueryStringProperty<PalierClient>(_entities[5].properties[3]);

  /// See [PalierClient.level].
  static final level =
      obx.QueryIntegerProperty<PalierClient>(_entities[5].properties[4]);
}

/// [PointRelais] entity fields to define ObjectBox queries.
class PointRelais_ {
  /// See [PointRelais.id].
  static final id =
      obx.QueryIntegerProperty<PointRelais>(_entities[6].properties[0]);

  /// See [PointRelais.uid].
  static final uid =
      obx.QueryStringProperty<PointRelais>(_entities[6].properties[1]);

  /// See [PointRelais.libelle].
  static final libelle =
      obx.QueryStringProperty<PointRelais>(_entities[6].properties[2]);

  /// See [PointRelais.address].
  static final address =
      obx.QueryStringProperty<PointRelais>(_entities[6].properties[3]);

  /// See [PointRelais.description].
  static final description =
      obx.QueryStringProperty<PointRelais>(_entities[6].properties[4]);

  /// See [PointRelais.latitude].
  static final latitude =
      obx.QueryDoubleProperty<PointRelais>(_entities[6].properties[5]);

  /// See [PointRelais.longitude].
  static final longitude =
      obx.QueryDoubleProperty<PointRelais>(_entities[6].properties[6]);

  /// See [PointRelais.type].
  static final type = obx.QueryRelationToOne<PointRelais, TypePointRelais>(
      _entities[6].properties[7]);

  /// See [PointRelais.commune].
  static final commune =
      obx.QueryRelationToOne<PointRelais, Commune>(_entities[6].properties[8]);

  /// see [PointRelais.services]
  static final services = obx.QueryRelationToMany<PointRelais, TypeService>(
      _entities[6].relations[0]);

  /// see [PointRelais.schedules]
  static final schedules =
      obx.QueryRelationToMany<PointRelais, Schedule>(_entities[6].relations[1]);
}

/// [Schedule] entity fields to define ObjectBox queries.
class Schedule_ {
  /// See [Schedule.id].
  static final id =
      obx.QueryIntegerProperty<Schedule>(_entities[7].properties[0]);

  /// See [Schedule.uid].
  static final uid =
      obx.QueryStringProperty<Schedule>(_entities[7].properties[1]);

  /// See [Schedule.level_day].
  static final level_day =
      obx.QueryIntegerProperty<Schedule>(_entities[7].properties[2]);

  /// See [Schedule.available].
  static final available =
      obx.QueryBooleanProperty<Schedule>(_entities[7].properties[3]);

  /// See [Schedule.point_relais].
  static final point_relais =
      obx.QueryRelationToOne<Schedule, PointRelais>(_entities[7].properties[4]);

  /// See [Schedule.startHour].
  static final startHour =
      obx.QueryStringProperty<Schedule>(_entities[7].properties[5]);

  /// See [Schedule.endHour].
  static final endHour =
      obx.QueryStringProperty<Schedule>(_entities[7].properties[6]);
}

/// [StatusColis] entity fields to define ObjectBox queries.
class StatusColis_ {
  /// See [StatusColis.id].
  static final id =
      obx.QueryIntegerProperty<StatusColis>(_entities[8].properties[0]);

  /// See [StatusColis.uid].
  static final uid =
      obx.QueryStringProperty<StatusColis>(_entities[8].properties[1]);

  /// See [StatusColis.libelle].
  static final libelle =
      obx.QueryStringProperty<StatusColis>(_entities[8].properties[2]);

  /// See [StatusColis.description].
  static final description =
      obx.QueryStringProperty<StatusColis>(_entities[8].properties[3]);

  /// See [StatusColis.color].
  static final color =
      obx.QueryStringProperty<StatusColis>(_entities[8].properties[4]);

  /// See [StatusColis.level].
  static final level =
      obx.QueryIntegerProperty<StatusColis>(_entities[8].properties[5]);
}

/// [TypeClient] entity fields to define ObjectBox queries.
class TypeClient_ {
  /// See [TypeClient.id].
  static final id =
      obx.QueryIntegerProperty<TypeClient>(_entities[9].properties[0]);

  /// See [TypeClient.uid].
  static final uid =
      obx.QueryStringProperty<TypeClient>(_entities[9].properties[1]);

  /// See [TypeClient.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeClient>(_entities[9].properties[2]);

  /// See [TypeClient.level].
  static final level =
      obx.QueryIntegerProperty<TypeClient>(_entities[9].properties[3]);
}

/// [TypeColis] entity fields to define ObjectBox queries.
class TypeColis_ {
  /// See [TypeColis.id].
  static final id =
      obx.QueryIntegerProperty<TypeColis>(_entities[10].properties[0]);

  /// See [TypeColis.uid].
  static final uid =
      obx.QueryStringProperty<TypeColis>(_entities[10].properties[1]);

  /// See [TypeColis.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeColis>(_entities[10].properties[2]);

  /// See [TypeColis.level].
  static final level =
      obx.QueryIntegerProperty<TypeColis>(_entities[10].properties[3]);

  /// See [TypeColis.icone].
  static final icone =
      obx.QueryStringProperty<TypeColis>(_entities[10].properties[4]);

  /// See [TypeColis.description].
  static final description =
      obx.QueryStringProperty<TypeColis>(_entities[10].properties[5]);

  /// See [TypeColis.poids_min].
  static final poids_min =
      obx.QueryDoubleProperty<TypeColis>(_entities[10].properties[6]);

  /// See [TypeColis.poids_max].
  static final poids_max =
      obx.QueryDoubleProperty<TypeColis>(_entities[10].properties[7]);

  /// See [TypeColis.price].
  static final price =
      obx.QueryIntegerProperty<TypeColis>(_entities[10].properties[8]);

  /// See [TypeColis.emballage].
  static final emballage = obx.QueryRelationToOne<TypeColis, TypeEmballage>(
      _entities[10].properties[9]);

  /// See [TypeColis.vehicule].
  static final vehicule = obx.QueryRelationToOne<TypeColis, TypeVehicule>(
      _entities[10].properties[10]);
}

/// [TypeDestinataire] entity fields to define ObjectBox queries.
class TypeDestinataire_ {
  /// See [TypeDestinataire.id].
  static final id =
      obx.QueryIntegerProperty<TypeDestinataire>(_entities[11].properties[0]);

  /// See [TypeDestinataire.uid].
  static final uid =
      obx.QueryStringProperty<TypeDestinataire>(_entities[11].properties[1]);

  /// See [TypeDestinataire.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeDestinataire>(_entities[11].properties[2]);

  /// See [TypeDestinataire.description].
  static final description =
      obx.QueryStringProperty<TypeDestinataire>(_entities[11].properties[3]);

  /// See [TypeDestinataire.level].
  static final level =
      obx.QueryIntegerProperty<TypeDestinataire>(_entities[11].properties[4]);
}

/// [TypeEmballage] entity fields to define ObjectBox queries.
class TypeEmballage_ {
  /// See [TypeEmballage.id].
  static final id =
      obx.QueryIntegerProperty<TypeEmballage>(_entities[12].properties[0]);

  /// See [TypeEmballage.uid].
  static final uid =
      obx.QueryStringProperty<TypeEmballage>(_entities[12].properties[1]);

  /// See [TypeEmballage.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeEmballage>(_entities[12].properties[2]);

  /// See [TypeEmballage.price].
  static final price =
      obx.QueryIntegerProperty<TypeEmballage>(_entities[12].properties[3]);

  /// See [TypeEmballage.level].
  static final level =
      obx.QueryIntegerProperty<TypeEmballage>(_entities[12].properties[4]);
}

/// [TypePointRelais] entity fields to define ObjectBox queries.
class TypePointRelais_ {
  /// See [TypePointRelais.id].
  static final id =
      obx.QueryIntegerProperty<TypePointRelais>(_entities[13].properties[0]);

  /// See [TypePointRelais.uid].
  static final uid =
      obx.QueryStringProperty<TypePointRelais>(_entities[13].properties[1]);

  /// See [TypePointRelais.libelle].
  static final libelle =
      obx.QueryStringProperty<TypePointRelais>(_entities[13].properties[2]);
}

/// [TypeService] entity fields to define ObjectBox queries.
class TypeService_ {
  /// See [TypeService.id].
  static final id =
      obx.QueryIntegerProperty<TypeService>(_entities[14].properties[0]);

  /// See [TypeService.uid].
  static final uid =
      obx.QueryStringProperty<TypeService>(_entities[14].properties[1]);

  /// See [TypeService.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeService>(_entities[14].properties[2]);
}

/// [TypeVehicule] entity fields to define ObjectBox queries.
class TypeVehicule_ {
  /// See [TypeVehicule.id].
  static final id =
      obx.QueryIntegerProperty<TypeVehicule>(_entities[15].properties[0]);

  /// See [TypeVehicule.uid].
  static final uid =
      obx.QueryStringProperty<TypeVehicule>(_entities[15].properties[1]);

  /// See [TypeVehicule.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeVehicule>(_entities[15].properties[2]);

  /// See [TypeVehicule.icone].
  static final icone =
      obx.QueryStringProperty<TypeVehicule>(_entities[15].properties[3]);

  /// See [TypeVehicule.level].
  static final level =
      obx.QueryIntegerProperty<TypeVehicule>(_entities[15].properties[4]);
}
