// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/ClientApp/Client.dart';
import 'models/ClientApp/CustomUser.dart';
import 'models/ClientApp/TypeClient.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5771063439127381654),
      name: 'Client',
      lastPropertyId: const obx_int.IdUid(9, 660162159130486979),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7248952066763326882),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3790223563815779843),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 937734708588133838)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8014211537744612000),
            name: 'contact',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1811766398683889147),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4461514141245376921),
            name: 'active',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1147669443491728784),
            name: 'typeClientId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 7009378504581188781),
            relationTarget: 'TypeClient'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 660162159130486979),
            name: 'userId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 2851602042184770898),
            relationTarget: 'CustomUser')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 6491705102151008622),
      name: 'CustomUser',
      lastPropertyId: const obx_int.IdUid(4, 5655375414535947178),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1210364152626561817),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3610877587995571284),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(3, 7165414412306323077)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7767288833102030863),
            name: 'firstName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5655375414535947178),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7639888620761706740),
      name: 'TypeClient',
      lastPropertyId: const obx_int.IdUid(4, 5199914493409409280),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6071177071569330440),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4682769578849025609),
            name: 'uid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(4, 7587553272518223579)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8471050322517988185),
            name: 'libelle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5199914493409409280),
            name: 'level',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 7639888620761706740),
      lastIndexId: const obx_int.IdUid(5, 2851602042184770898),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [867977961967318551, 4714811330399576640],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Client: obx_int.EntityDefinition<Client>(
        model: _entities[0],
        toOneRelations: (Client object) => [object.typeClient, object.user],
        toManyRelations: (Client object) => {},
        getId: (Client object) => object.id,
        setId: (Client object, int id) {
          object.id = id;
        },
        objectToFB: (Client object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final contactOffset = fbb.writeString(object.contact);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(4, contactOffset);
          fbb.addOffset(5, addressOffset);
          fbb.addBool(6, object.active);
          fbb.addInt64(7, object.typeClient.targetId);
          fbb.addInt64(8, object.user.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final contactParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final activeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final object = Client(
              uid: uidParam,
              contact: contactParam,
              address: addressParam,
              active: activeParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.typeClient.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.typeClient.attach(store);
          object.user.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.user.attach(store);
          return object;
        }),
    CustomUser: obx_int.EntityDefinition<CustomUser>(
        model: _entities[1],
        toOneRelations: (CustomUser object) => [],
        toManyRelations: (CustomUser object) => {},
        getId: (CustomUser object) => object.id,
        setId: (CustomUser object, int id) {
          object.id = id;
        },
        objectToFB: (CustomUser object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final firstNameOffset = fbb.writeString(object.firstName);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, firstNameOffset);
          fbb.addInt64(3, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final firstNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = CustomUser(
              uid: uidParam, firstName: firstNameParam, level: levelParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TypeClient: obx_int.EntityDefinition<TypeClient>(
        model: _entities[2],
        toOneRelations: (TypeClient object) => [],
        toManyRelations: (TypeClient object) => {},
        getId: (TypeClient object) => object.id,
        setId: (TypeClient object, int id) {
          object.id = id;
        },
        objectToFB: (TypeClient object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final libelleOffset = fbb.writeString(object.libelle);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, libelleOffset);
          fbb.addInt64(3, object.level);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final libelleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final levelParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = TypeClient(
              uid: uidParam, libelle: libelleParam, level: levelParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Client] entity fields to define ObjectBox queries.
class Client_ {
  /// See [Client.id].
  static final id =
      obx.QueryIntegerProperty<Client>(_entities[0].properties[0]);

  /// See [Client.uid].
  static final uid =
      obx.QueryStringProperty<Client>(_entities[0].properties[1]);

  /// See [Client.contact].
  static final contact =
      obx.QueryStringProperty<Client>(_entities[0].properties[2]);

  /// See [Client.address].
  static final address =
      obx.QueryStringProperty<Client>(_entities[0].properties[3]);

  /// See [Client.active].
  static final active =
      obx.QueryBooleanProperty<Client>(_entities[0].properties[4]);

  /// See [Client.typeClient].
  static final typeClient =
      obx.QueryRelationToOne<Client, TypeClient>(_entities[0].properties[5]);

  /// See [Client.user].
  static final user =
      obx.QueryRelationToOne<Client, CustomUser>(_entities[0].properties[6]);
}

/// [CustomUser] entity fields to define ObjectBox queries.
class CustomUser_ {
  /// See [CustomUser.id].
  static final id =
      obx.QueryIntegerProperty<CustomUser>(_entities[1].properties[0]);

  /// See [CustomUser.uid].
  static final uid =
      obx.QueryStringProperty<CustomUser>(_entities[1].properties[1]);

  /// See [CustomUser.firstName].
  static final firstName =
      obx.QueryStringProperty<CustomUser>(_entities[1].properties[2]);

  /// See [CustomUser.level].
  static final level =
      obx.QueryIntegerProperty<CustomUser>(_entities[1].properties[3]);
}

/// [TypeClient] entity fields to define ObjectBox queries.
class TypeClient_ {
  /// See [TypeClient.id].
  static final id =
      obx.QueryIntegerProperty<TypeClient>(_entities[2].properties[0]);

  /// See [TypeClient.uid].
  static final uid =
      obx.QueryStringProperty<TypeClient>(_entities[2].properties[1]);

  /// See [TypeClient.libelle].
  static final libelle =
      obx.QueryStringProperty<TypeClient>(_entities[2].properties[2]);

  /// See [TypeClient.level].
  static final level =
      obx.QueryIntegerProperty<TypeClient>(_entities[2].properties[3]);
}
